<?php
$GLOBALS['PROJECT_ROOT'] = '';
$GLOBALS['PROJECT_ROOT_DIR'] = $_SERVER['DOCUMENT_ROOT'] . $GLOBALS['PROJECT_ROOT'];
$GLOBALS['REQUIRES_ACCESS'] = false;
$GLOBALS['ADMIN_REQUIRES_ACCESS'] = true;